-- CRIA TABELA ALUNO --

CREATE TABLE ALUNO(
CPF VARCHAR(15),
NOME VARCHAR(80) CONSTRAINT NN_AL_NOME NOT NULL,
SEXO CHAR(1),
NASC DATE,
END_CEP VARCHAR(10),
END_COMP VARCHAR(20),
END_N VARCHAR(5),
CONSTRAINT PK_ALUNO PRIMARY KEY(CPF),
CONSTRAINT AK_AL_CPF UNIQUE (NOME, NASC)

);

-- CRIA TABELA TELEFONE_ALUNO --

CREATE TABLE TELEFONE_ALUNO(
CPF VARCHAR(15),
TELEFONET VARCHAR(10),
CONSTRAINT FK_TELEFONET FOREIGN KEY(CPF) REFERENCES  ALUNO(CPF),
CONSTRAINT PK_TELEFONET PRIMARY KEY(CPF,TELEFONET)

);


-- CRIA TABELA EMERGENCIA --

CREATE TABLE EMERGENCIA(
ID VARCHAR(10),
NOME VARCHAR(80),
NUMERO VARCHAR(10),
CPF_ALUNO VARCHAR(15) UNIQUE CONSTRAINT NN_CPF NOT NULL,
CONSTRAINT PK_EMERGENCIA PRIMARY KEY(ID),
CONSTRAINT FK_EMERGENCIA FOREIGN KEY(CPF_ALUNO) REFERENCES  ALUNO(CPF)
);

-- CRIA TABELA FICHA DE TREINO --

CREATE TABLE FICHA_DE_TREINO(
COD CHAR(1),
EXERCICIOS VARCHAR(200),
CONSTRAINT PK_FICHA PRIMARY KEY(COD)
);


-- CRIA TABELA PROMOÇÃO --

CREATE TABLE PROMOCAO(
ID_PROMO VARCHAR(10),
DESCONTO NUMBER(3, 1),
CONSTRAINT PK_PROMO PRIMARY KEY(ID_PROMO)
);

-- CRIA TABELA ACADEMIA --

CREATE TABLE ACADEMIA(
ID VARCHAR(15),
END_CEP VARCHAR(10),
END_N VARCHAR(5),
CONSTRAINT PK_ACAD PRIMARY KEY(ID)
);

-- CRIAR TABELA EQUIPAMENTOS -- 

CREATE TABLE EQUIPAMENTOS(
NOME VARCHAR(200),
ID VARCHAR(200),
CONSTRAINT FK_EQUIP FOREIGN KEY(ID) REFERENCES ACADEMIA(ID),
CONSTRAINT PK_EQUIP PRIMARY KEY(ID,NOME)

);

-- CRIA TABELA MAQUINAS --

CREATE TABLE MAQUINAS(
ID_MAQ VARCHAR(10),
ID_ACAD VARCHAR(10),
NOME VARCHAR(25),
DT_MANU DATE,
CONSTRAINT FK_MAQUINA FOREIGN KEY(ID_ACAD,NOME) REFERENCES EQUIPAMENTOS(ID,NOME),
CONSTRAINT PK_MAQ PRIMARY KEY(ID_ACAD,NOME,ID_MAQ)
);


-- CRIA TABELA PLANO  --

CREATE TABLE PLANO(
COD VARCHAR(6),
CONSTRAINT PK_PLAN PRIMARY KEY(COD)
);

-- CRIA TABELA SIMPLES-- 

CREATE TABLE SIMPLES(
COD_PLANO VARCHAR(6),
PREÇO_S NUMBER(5,2),
ID_ACAD VARCHAR(15),
PERIODO_S NUMBER(2),
CONSTRAINT FK_SIMPLES FOREIGN KEY(COD_PLANO) REFERENCES PLANO(COD),
CONSTRAINT FK_ID_ACAD FOREIGN KEY(ID_ACAD) REFERENCES ACADEMIA(ID),
CONSTRAINT PK_SIMPLE PRIMARY KEY(COD_PLANO, ID_ACAD, PERIODO_S)
);

-- CRIA TABELA PREMIUM --

CREATE TABLE PREMIUM(
COD_PLANO VARCHAR(6),
PREÇO_P NUMBER(5,2),
PERIODO_P NUMBER(2),
CONSTRAINT FK_PREMIUM FOREIGN KEY(COD_PLANO) REFERENCES PLANO(COD),
CONSTRAINT PK_PREMIUM PRIMARY KEY(COD_PLANO, PERIODO_P)
);

-- CRIA TABELA ACESSO_P --

CREATE TABLE ACESSO_P(
ID_ACAD VARCHAR(10),
COD_ACESSO VARCHAR(6),
PERIODO_ACESSO NUMBER(2),
CONSTRAINT FK_ACESSO_ACAD FOREIGN KEY(ID_ACAD) REFERENCES ACADEMIA(ID),
CONSTRAINT FK_ACESSO_PLAN FOREIGN KEY(COD_ACESSO, PERIODO_ACESSO) REFERENCES PREMIUM(COD_PLANO,PERIODO_P),
CONSTRAINT PK_ACESSO PRIMARY KEY(ID_ACAD, COD_ACESSO, PERIODO_ACESSO)    
);

-- CRIA TABELA FUNCIONARIOS --

CREATE TABLE FUNCIONARIOS(
CPF VARCHAR(15),
NOME VARCHAR(80),
END_CEP VARCHAR(10),
END_COMP VARCHAR(20),
END_N VARCHAR(5),
ID_ACAD VARCHAR(7) CONSTRAINT NN_ID_ACAD NOT NULL,
CPF_GERENTE VARCHAR(15),
CONSTRAINT FK_FUNC FOREIGN KEY(ID_ACAD) REFERENCES ACADEMIA(ID),
CONSTRAINT FK_FUNC2 FOREIGN KEY(CPF_GERENTE) REFERENCES FUNCIONARIOS(CPF),
CONSTRAINT PK_FUNC PRIMARY KEY(CPF)
);

-- CRIA TABELA TELEFONEFUNC --

CREATE TABLE TELEFONE_FUNC(
CPF_FUNC VARCHAR(15),
TELEFONEF VARCHAR(10),
CONSTRAINT FK_TELEFUNC FOREIGN KEY(CPF_FUNC) REFERENCES FUNCIONARIOS(CPF),
CONSTRAINT PK_TELEFUNC PRIMARY KEY(CPF_FUNC,TELEFONEF)
);

-- CRIA TABELA PROFESSOR --

CREATE TABLE PROFESSOR(
CPF VARCHAR(15),
CONSTRAINT FK_PROF FOREIGN KEY(CPF) REFERENCES FUNCIONARIOS(CPF),
CONSTRAINT PK_PROF PRIMARY KEY(CPF)    
);

-- CRIA TABELA CADASTRO --

CREATE TABLE CADASTRO(
CPF VARCHAR(15),
COD VARCHAR(6),
DT DATE,
ID_PROMO VARCHAR(10),
CONSTRAINT FK_CADASTRO1 FOREIGN KEY(CPF) REFERENCES ALUNO(CPF), 
CONSTRAINT FK_CADASTRO2 FOREIGN KEY(COD) REFERENCES PLANO(COD), 
CONSTRAINT FK_CADASTRO3 FOREIGN KEY(ID_PROMO) REFERENCES PROMOCAO(ID_PROMO), 
CONSTRAINT PK_CADASTRO PRIMARY KEY(CPF,COD,DT) 
);

-- CRIA TABELA TREINO --

CREATE TABLE TREINO(
COD CHAR(1),
CPF_ALUNO VARCHAR(15),
CPF_PROF VARCHAR(15) CONSTRAINT NN_CPF_PROF NOT NULL,
CONSTRAINT FK_TREINO1 FOREIGN KEY(COD) REFERENCES FICHA_DE_TREINO(COD),
CONSTRAINT FK_TREINO2 FOREIGN KEY(CPF_ALUNO) REFERENCES ALUNO(CPF),
CONSTRAINT FK_TREINO3 FOREIGN KEY(CPF_PROF) REFERENCES PROFESSOR(CPF),
CONSTRAINT PK_TREINO PRIMARY KEY(COD,CPF_ALUNO)
);
